[pytest]
addopts = -q -ra --cov=app --cov-config=pytest.ini --cov-report=term-missing --maxfail=1 --disable-warnings
filterwarnings =
    error::DeprecationWarning
    ignore::pytest.PytestUnraisableExceptionWarning
markers =
    integration: marks integration tests

pythonpath = .

asyncio_mode = strict
asyncio_default_fixture_loop_scope = function

[coverage:run]
omit =
    app/seed.py